// Code generated by file2byteslice. DO NOT EDIT.

package resources

var ConfigJson = []byte("{\r\n    \"screenWidth\": 540,\r\n    \"screenHeight\": 580,\r\n    \"title\": \"外星人入侵\",\r\n    \"bgColor\": {\r\n        \"r\": 230,\r\n        \"g\": 230,\r\n        \"b\": 230,\r\n        \"a\": 255\r\n    },\r\n    \"playerSpeedFactor\": 5,\r\n    \"alienSpeedFactor\": 1,\r\n    \"bossSpeedFactor\": 1,\r\n    \"bulletWidth\": 3,\r\n    \"bulletHeight\": 10,\r\n    \"bulletSpeedFactor\": 5,\r\n    \"bulletColor\": {\r\n        \"r\": 80,\r\n        \"g\": 80,\r\n        \"b\": 80,\r\n        \"a\": 255\r\n    },\r\n    \"maxBulletNum\": 100,\r\n    \"bulletInterval\": 100,\r\n    \"titleFontSize\": 10,\r\n    \"fontSize\": 30,\r\n    \"smallFontSize\": 10\r\n}")
