// Code generated by file2byteslice. DO NOT EDIT.

package resources
import (
    _ "embed"
)

//go:embed images/alien.png
var AlienPng []byte

//go:embed images/blast.png
var BlastPng []byte

//go:embed images/boss.png
var BossPng []byte

//go:embed images/gopher.png
var GopherPng []byte

//go:embed images/player.png
var PlayerPng []byte
